# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target :'Buxury' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Buxury
  pod 'AWSMobileClient'
  pod 'AWSAuthUI'
  pod 'AWSUserPoolsSignIn'
  pod 'AWSAppSync'

  target :'BuxuryTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target :'BuxuryUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
